sql_query_task:
  description: >
    Usa la plantilla SQL especificada en {sql_template}, que contiene placeholders nombrados como ':param_name'.
    Debes proporcionar los valores para estos placeholders en un diccionario JSON en {parameter_values}.
    El objetivo es analizar datos para el cliente: {customer_infoname}.
    La herramienta ejecutará la consulta de forma segura.

    FORMATO DE INPUTS REQUERIDO:
    sql_template: "SELECT columna FROM tabla WHERE nombre_cliente = :cliente AND categoria = :cat"
    parameter_values: {{"cliente": "Nombre del cliente", "cat": "ValorCategoría"}} # Diccionario JSON
    customer_infoname: "Nombre del cliente"

    - HACER:
      - SIEMPRE usa el formato de diccionario JSON para parameter_values.
      - Asegúrate de que las claves del diccionario coincidan con los placeholders :nombre en la plantilla SQL.
    - NO HACER:
      - No uses listas para parameter_values.
      - No uses placeholders '?' en sql_template.
      - No intentes ejecutar SQL directamente; pasa la plantilla y el diccionario de parámetros.
    No omitas este paso.
    # tool_input: ['sql_template', 'parameter_values', 'customer_infoname'] # Esto sigue igual
  expected_output: >
    Estructura el resultado como una tabla Markdown ``` ```. Sin explicaciones.

compose_offer_document_task:
  description: >
    Tomar la información obtenida por la tarea sql_query_task 
    y formatearla en dos versiones: un resumen textual conciso 
    y una tabla detallada en Markdown.
  expected_output: >
    Un string JSON que contenga un objeto con dos claves:
    - 'summary': Un string con el resumen en texto plano, adecuado para chat.
    - 'details_markdown': Un string con la tabla detallada en formato Markdown (``` ```).
    



