sql_query_task:
  description: >
    Usa la plantilla SQL especificada: {sql_template} y el diccionario de valores de parámetros: {parameter_values} 
    para analizar los datos del cliente: {customer_infoname}.
    La herramienta ejecutará la consulta de forma segura usando los parámetros nombrados (:param_name) proporcionados en el diccionario.
    Asegúrate de que los inputs coinciden con el formato requerido.
    
    EJEMPLO FORMATO DE INPUTS REQUERIDO:
    sql_template: "Tu plantilla SQL con :nombre_param aquí"
    parameter_values: {"nombre_param": "Valor"} # Ejemplo simplificado
    customer_infoname: "Nombre del cliente"

    - HACER:
      - SIEMPRE usa el formato de inputs especificado arriba.
      - Asegúrate de que la plantilla SQL use ':nombre_param' como placeholders.
      - Asegúrate de que el diccionario `parameter_values` contenga claves que coincidan con todos los placeholders en la plantilla.

    - NO HACER:
      - No uses formatos de input diferentes al especificado.
      - No intentes ejecutar SQL directamente en la descripción; pasa la plantilla y el diccionario de parámetros.

    No omitas este paso.
    - tool_input: ['sql_template', 'parameter_values', 'customer_infoname'] # Estos nombres deben coincidir con los inputs del kickoff
    
  expected_output: >
    Estructura el resultado que obtengas de la ejecución de la consulta como una tabla
    que contenga los datos en formato markdown ``` ```. No habrá 
    explicaciones ni comentarios.

compose_offer_document_task:
  description: >
    Generar un documento de cotización en PDF usando la 
    información proporcionada por la herramienta CustomNL2SQLTool
    en la tarea sql_query_task.
  expected_output: >
    Un documento estructurado de cotización en formato PDF que contenga el
    nombre del cliente, la fecha de la cotizacion, junto con las imagenes, 
    codigos, descripciones, marcas cantidades, precios de los productos 
    que están en stock y totales.



