sql_query_task:
  description: >
    Usa la plantilla SQL especificada: {sql_template} y los valores de parámetros: {parameter_values} 
    para analizar los datos del cliente: {customer_infoname}.
    La herramienta ejecutará la consulta de forma segura. 
    Si la plantilla SQL usa placeholders posicionales (?), `parameter_values` debe ser una lista de valores en el orden correcto.
    Si la plantilla SQL usa placeholders nombrados (:param_name), `parameter_values` debe ser un diccionario con claves que coincidan.
    Asegúrate de que los inputs coinciden con el formato requerido.
    
    EJEMPLO FORMATO DE INPUTS REQUERIDO (para placeholders '?'):
    sql_template: "SELECT columna FROM tabla WHERE columna1 = ? AND columna2 = ?"
    parameter_values: ["valor1", "valor2"] # Lista de valores
    customer_infoname: "Nombre del cliente"

    - HACER:
      - SIEMPRE usa el formato de inputs especificado arriba según el tipo de placeholder.
      - Asegúrate de que `parameter_values` coincida en tipo y contenido con los placeholders de la plantilla SQL.

    - NO HACER:
      - No uses formatos de input diferentes al especificado.
      - No intentes ejecutar SQL directamente en la descripción; pasa la plantilla y los parámetros.

    No omitas este paso.
    - tool_input: ['sql_template', 'parameter_values', 'customer_infoname'] # Estos nombres deben coincidir con los inputs del kickoff
    
  expected_output: >
    Estructura el resultado que obtengas de la ejecución de la consulta como una tabla
    que contenga los datos en formato markdown ``` ```. No habrá 
    explicaciones ni comentarios.

compose_offer_document_task:
  description: >
    Generar un documento de cotización en PDF usando la 
    información proporcionada por la herramienta CustomNL2SQLTool
    en la tarea sql_query_task.
  expected_output: >
    Un documento estructurado de cotización en formato PDF que contenga el
    nombre del cliente, la fecha de la cotizacion, junto con las imagenes, 
    codigos, descripciones, marcas cantidades, precios de los productos 
    que están en stock y totales.



