name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.8'

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Build project
      run:
        echo "Running build Script"

    - name: Deploy to Cloud
      run: |
        echo "Running deployment script"
        cd src
        python3 -m agente_tab.main run
